### ISSUE TITLE
What's the difference between popupwindow?

### ISSUE THREAD

**Issue by FynnJason** [AnthonyFermin/DropDownView#2]
Hello, I think it's more complicated than popupwindow.

**Comment by AnthonyFermin** [comment]
Hello, if `PopupWindow` works for you, then you should definitely use that. When you're trying to change `PopupWindow` to behave a different way than initially intended, then that's when you might need a custom view. I found myself needing this code more often so I abstracted it out and shared it with the world.

Also, `DropDownView` is simply part of your view hierarchy so there may be different use cases that may warrant the use of this view vs `PopupWindow`. The main features of this view is the built in expand/collapse animations and 60% alpha overlay below the view.
